# Generated by Django 4.2.7 on 2023-11-11 09:29

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fileTransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='shareable_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'txt'])]),
        ),
    ]
